### ISSUE TITLE
SVG files don't open in Inkscape

### ISSUE THREAD

**Issue by ilyagr** [slowli/term-transcript#52]
Opening files generated by `term-transcript` in inkscape results in a black rectangle for me.

Most similar tools to term-transcript that I tried share this problem. https://github.com/marionebl/svg-term-cli is a notable exception; it generates files that look fine in Inkscape.

This is similar to #49. I'm filing this issue for completeness and for reference rather than to suggest it as a priority. I'm not sure how useful it is to edit such SVG files in Inkscape.

Inkscape can convert the text in the file to paths, which makes the SVG independent of fonts installed on the system, but the cost is that the file becomes much larger and unreadable. Inkscape is affected by #51 just like web browsers are. Unicode characters may look differently depending on which fonts you have installed.

**Comment by slowli** [comment]
This is because term-transcript uses a workaround for the problem of typesetting inputs / outputs (which given monospace fonts is not as difficult as the general case, but still quite complex). Instead of typesetting, term-transcript embeds HTML, which knows how to typeset everything automatically by design. The downside of this approach is that HTML embedding is not supported by some tools, Inkscape included. (It's obviously supported by all browsers since browsers know how to render HTML anyway.)

It is possible to conditionally render parts of SVG depending whether or not the HTML embedding is supported. This can be used to render an error message if embedding is not supported, which I plan to implement / test as a near-term workaround (not really a fix, but still better than a black rectangle). A more comprehensive solution would require implementing typesetting logic in some way, which looks quite complex.
